name: Fsharp Check Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.fs'
      - '**.fsx'
      - '**.fsproj'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

# Kill other jobs when we trigger this workflow by sending new commits
# to the PR.
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fantomas-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: .NET tool restore
        run: dotnet tool install --global fantomas --version 6.0.2

      - name: Check lint for src/
        run: fantomas -r --check .github/fsharp-custom-action/src

      - name: Check lint for tests/
        run: fantomas -r --check .github/fsharp-custom-action/tests
