name: Terraform Apply

on:
  workflow_dispatch: # manual trigger
    inputs:
      project:
        type: choice
        required: true
        description: What project to apply
        options:
        - instance-1
        - instance-2
      module:
        type: choice
        required: true
        description: Which module to apply
        options:
        - network
        - virtual-machine

env:
  PROJECT_DIRECTORY: terraform/${{ github.event.inputs.project }}/${{ github.event.inputs.module }}
        
jobs:
  # Apply the configuration in the production environment.
  apply:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./${{ env.PROJECT_DIRECTORY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform plan
        run: terraform plan -out tfplan
      - name: Terraform apply
        run: terraform apply "tfplan"
